config/routes.rb
Rails.application.routes.draw do
  resources :markers
  resources :categories
  resources :archetypes
  get "api/category/:id", to: "categories#api"
  get 'home/index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archetype.rb
class Archetype < ApplicationRecord
    has_many :markers
    validates :name, presence: true
    # accepts_nested_attributes_for :markers, reject_if: :all_blank
end

app/models/category.rb
class Category < ApplicationRecord
    enum status: [:publico, :privado]
    has_many :markers
    has_many :categories, dependent: :destroy
    belongs_to :category, optional: true
    validates :name, :status, presence: true
    # accepts_nested_attributes_for :markers, reject_if: :all_blank
end

app/models/marker.rb
class Marker < ApplicationRecord
    belongs_to :category, dependent: :destroy
    belongs_to :archetype, dependent: :destroy
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archetypes_controller.rb
class ArchetypesController < ApplicationController
  
  def index
    @archetypes = Archetype.all
    @archetype = Archetype.new
  end

  def show
    @archetypes = Archetype.all
  end

  def new
    @archetype = Archetype.new
  end

  def create
    @archetype = Archetype.new(archetype_params)
    respond_to do |format|
        if @archetype.save!
          format.html { redirect_to archetypes_path, notice: "El Tipo fue creado correctamente" }
        else
          format.html { render :new}
        end
    end
  end

  def edit
		@archetype = Archetype.find(params[:id])
	end

  def update
    @archetype = Archetype.find(params[:id])
    respond_to do |format|
      if @archetype.update(archetype_params)
        format.html { redirect_to @archetype, notice: "El Tipo fue actualizado correctamente" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @archetype = Archetype.find(params[:id])
    @archetype.destroy
    respond_to do |format|
      format.html { redirect_to @archetype, notice: "El Tipo fue eliminado correctamente" }
    end
  end

  private

  def archetype_params
    params.require(:archetype).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def api
    @category = Category.find(params[:id])
    render json: @category.to_json(include: [:categories, :markers])
  end
  
  def index
    @categories = Category.all
    @category = Category.new
  end

  def show
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
        if @category.save!
          if @category.category_id == ""
            @category.update(category_id: nil)
          end
          format.html { redirect_to categories_path, notice: "La Categoria fue creada correctamente" }
        else
          format.html { render :new}
        end
    end
  end

  def edit
		@category = Category.find(params[:id])
    @categories = Category.all
	end

	def update
    @categories = Category.all
		@category = Category.find(params[:id])
		respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "La Categoria fue actualizado correctamente" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
		end
	end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.html { redirect_to @category, notice: "La Categoria fue eliminado correctamente" }
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :status, :category_id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    @archetypes = Archetype.all
    @markers = Marker.all
    @marker_archetype = @markers.map { |marker| marker.archetype_id}
    @marker_archetype_name = @marker_archetype.map {|k, archetype_id| Archetype.find(archetype_id).name}
    @marker_graph = @marker_archetype_name.group(:name).count

  end

end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  
  def index
    @markers = Marker.all
    @marker = Marker.new
    @categories = Category.all
    @archetypes = Archetype.all
  end

  def show
    @markers = Marker.all
  end

  def new
    @marker = Marker.new
    @categories = Category.all
    @archetypes = Archetype.all
  end

  def create
    @marker = Marker.new(marker_params)
    @categories = Category.all
    @archetypes = Archetype.all
    respond_to do |format|
        if @marker.save!
          # format.html { redirect_to markers_path, notice: "El Marcador fue creado correctamente" }
          format.js { render nothing: true, notice: 'El Marcador fue creado correctamente' }
        else
          format.html { render :new}
        end
    end
  end

  def edit
		@marker = Marker.find(params[:id])
    @categories = Category.all
    @archetypes = Archetype.all
	end

	def update
		@marker = Marker.find(params[:id])
    @categories = Category.all
    @archetypes = Archetype.all
		respond_to do |format|
      if @marker.update(marker_params)
        # format.html { redirect_to markers_path, notice: "El Marcador fue actualizado correctamente" }
        format.js { render nothing: true, notice: 'El Marcador fue actualizado correctamente' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
		end
	end
  
  def destroy
    @marker = Marker.find(params[:id])
    @marker.destroy
    respond_to do |format|
      # format.html { redirect_to marker_url, notice: "El Marcador fue eliminado correctamente" }
      format.js { render nothing: true, notice: 'El Marcador fue eliminado correctamente' }
    end
  end

  private

  def marker_params
    params.require(:marker).permit(:name, :category_id, :archetype_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archetypes_helper.rb
module ArchetypesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/archetypes/_form.html.erb
<%= form_with(model: @archetype, remote: true) do |f| %>
    <% if @archetype.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este Tipo no se pudo crear por las siguientes razones</h2>
            <ul>
                <% @archetype.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <h3>Ingrese su Tipo</h3>
    
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, placeholder: 'Escriba el nombre de su Tipo', class: "form-control" %>
    </div>

    <div class = 'actions'>
        <%= f.submit "Guardar Tipo", class:'btn btn-success border-dark mb-2'%>
    </div>
    <button class="btn btn-danger btn-md active"><%= link_to 'Volver al Inicio', root_path, class:'text-white'%></button>
<% end %>

app/views/archetypes/create.html.erb
<h1>Archetypes#create</h1>
<p>Find me in app/views/archetypes/create.html.erb</p>

app/views/archetypes/destroy.html.erb
<h1>Archetypes#destroy</h1>
<p>Find me in app/views/archetypes/destroy.html.erb</p>

app/views/archetypes/edit.html.erb
<div class="container">
  <%= render 'archetypes/form', archetype: @archetype %>
</div>

app/views/archetypes/index.html.erb
<div class="container">
  <%= render 'archetypes/form' %>
</div>

<h3 class="category-title text-center">Listado de Tipos</h3>

<table class="table table-striped">
    <thead id="tabla">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody id="archetypes">
        <% @archetypes.each do |a| %>
            <tr>
                <td><%= a.id %></td>
                <td><%= a.name %></td>
                <td><%= link_to 'Editar', edit_archetype_path(a) %></td>
                <td><%= link_to 'Eliminar', archetype_path(a), method: :delete, data: { confirm: '¿Esta seguro que desea eliminar el Tipo?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/archetypes/new.html.erb
<h1>Archetypes#new</h1>
<p>Find me in app/views/archetypes/new.html.erb</p>

app/views/archetypes/show.html.erb
<h3 class="category-title text-center">Listado de Tipos</h3>

<table class="table table-striped">
    <thead id="tabla">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody id="archetypes">
        <% @archetypes.each do |a| %>
            <tr>
                <td><%= a.id %></td>
                <td><%= a.name %></td>
                <td><%= link_to 'Editar', edit_archetype_path(a) %></td>
                <td><%= link_to 'Eliminar', archetype_path(a), method: :delete, data: { confirm: '¿Esta seguro que desea eliminar el Tipo?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<button class="btn btn-danger btn-md active"><%= link_to 'Volver al Inicio', root_path, class:'text-white'%></button>

app/views/archetypes/update.html.erb
<h1>Archetypes#update</h1>
<p>Find me in app/views/archetypes/update.html.erb</p>

app/views/categories/_form.html.erb
<%= form_with(model: @category, remote: true) do |f| %>
    <% if @category.errors.any? %>
        <div id = 'error_explanation'>
            <h2 class= "text-danger font-weight-bold">Atención! Existe <%= pluralize(category.errors.count, "error") %> el cual no permite guardar la Categoria</h2>
            <ul>
                <% @category.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <h3>Ingrese su Categoria</h3>
    
    <div class="form-group">
        <%= f.label :nombre %>
        <%= f.text_field :name, autofocus: true, placeholder: 'Escriba el nombre de su Categoria', class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :estado %>
        <%= f.select :status, [:publico, :privado], {}, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :categoria %>
        <br>
        <%= f.collection_select :category_id, @categories, :id, :name, include_blank: true%>
    </div>

    <div class = 'actions'>
        <%= f.submit "Guardar Categoria", class:'btn btn-success border-dark mb-2'%>
    </div>
    <button class="btn btn-danger btn-md active"><%= link_to 'Volver al Inicio', root_path, class:'text-white'%></button>

<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<div class="container">
  <%= render 'categories/form', category: @category %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <%= render 'categories/form' %>
</div>


<h3 class="category-title text-center">Listado de Categorias</h3>

<table class="table table-striped">
    <thead id="tabla">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Estado</th>
            <th>Categoria</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody id="categories">
        <% @categories.each do |c| %>
            <tr>
                <td><%= c.id %></td>
                <td><%= c.name %></td>
                <td><%= c.status %></td>
                <td>
                    <% if c.category_id != nil %>
                        <%= @categories.find(c.category_id).name %>
                    <% end %>
                </td>
                <td><%= link_to 'Editar', edit_category_path(c) %></td>
                <td><%= link_to 'Eliminar', category_path(c), method: :delete, data: { confirm: '¿Esta seguro que desea eliminar la Categoria?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h3 class="category-title text-center">Listado de Categorias</h3>

<table class="table table-striped">
    <thead id="tabla">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Estado</th>
            <th>Categoria</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody id="categories">
        <% @categories.each do |c| %>
            <tr>
                <td><%= c.id %></td>
                <td><%= c.name %></td>
                <td><%= c.status %></td>
                <td><%= link_to 'Editar', edit_category_path(c) %></td>
                <td><%= link_to 'Eliminar', category_path(c), method: :delete, data: { confirm: '¿Esta seguro que desea eliminar la Categoria?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<button class="btn btn-danger btn-md active"><%= link_to 'Volver al Inicio', root_path, class:'text-white'%></button>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/home/index.html.erb
<h1 class="category-title text-center">Sitio Público Bookmark</h1>

<div class="container">
    <button class="btn btn-primary btn-lg btn-block active"><%= link_to 'Revisar las Categorias', categories_path, class:'text-white'%></button>
    <br>
    <button class="btn btn-warning btn-lg btn-block active"><%= link_to 'Revisar los Tipos', archetypes_path, class:'text-white' %></button>
    <br>
    <button class="btn btn-success btn-lg btn-block active"><%= link_to 'Revisar los Marcadores', markers_path, class:'text-white' %></button>
    <h2 class="category-title text-center py-2">Gráfico Tipo Marcadores</h2>
    <%= pie_chart @marker_graph %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <p class="font-weight-bold text-dark alert-light pl-2 mt-2" ><%= notice %></p>
      <p class="font-weight-bold text-dark alert-light pl-2 mt-2" ><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/markers/_form.html.erb
<%= form_with(model: @marker, remote: true) do |f| %>
    <% if @marker.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este Marcador no se pudo crear por las siguientes razones</h2>
            <ul>
                <% @marker.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <h3>Ingrese su Marcador</h3>
    
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, placeholder: 'Escriba el nombre de su Marcador', class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :categoria %>
        <br>
        <%= f.collection_select :category_id, @categories, :id, :name%>
    </div>

    <div class="form-group">
        <%= f.label :tipo %>
        <br>
        <%= f.collection_select :archetype_id, @archetypes, :id, :name%>
    </div>

    <div class = 'actions' id="submit">
        <%= f.submit "Guardar Marcador", class:'btn btn-success border-dark mb-2', data: {confirm: 'Estas seguro?'} %>
    </div>

<% end %>

app/views/markers/_marker.html.erb
<tr id="marker-<%=@marker.id%>">
    <td><%= @marker.id %></td>
    <td><%= @marker.name %></td>
    <td><%= @categories.find(@marker.category_id).name %></td>
    <td><%= @archetypes.find(@marker.archetype_id).name %></td>
    <td><%= link_to 'Editar', edit_marker_path(@marker), remote: true, id: 'editbtn' %></td>
    <td><%= link_to 'Eliminar', marker_path(@marker), remote: true, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar el Marcador?' } %></td>
</tr>

app/views/markers/create.html.erb
<h1>Markers#create</h1>
<p>Find me in app/views/markers/create.html.erb</p>

app/views/markers/create.js.erb
$('#markers').append('<%= j render(@marker, marker: @marker) %>')
$('#mybutton').show();

app/views/markers/destroy.html.erb
<h1>Markers#destroy</h1>
<p>Find me in app/views/markers/destroy.html.erb</p>

app/views/markers/destroy.js.erb
$('#marker-<%=@marker.id%>').empty();

app/views/markers/edit.html.erb
<div class="container">
  <%= render 'markers/form', marker: @marker %>
</div>

app/views/markers/edit.js.erb
$('#form').append('<%= escape_javascript render('markers/form') %>');
$('#mybutton').hide();

app/views/markers/index.html.erb
<div id="mybutton">
    <%= link_to 'Nuevo Marcador', new_marker_path, class: 'btn btn-primary', remote: true %>
</div>

<div id="form">
</div>

<h3 class="category-title text-center">Listado de Marcadores</h3>

<table class="table table-striped">
    <thead id="tabla">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Categoria</th>
            <th>Tipo</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody id="markers">
        <% @markers.each do |m| %>
            <tr id="marker-<%=m.id%>">
                <td><%= m.id %></td>
                <td><%= m.name %></td>
                <td><%= @categories.find(m.category_id).name %></td>
                <td><%= @archetypes.find(m.archetype_id).name %></td>
                <td><%= link_to 'Editar', edit_marker_path(m), remote: true, id: 'editbtn' %></td>
                <td><%= link_to 'Eliminar', marker_path(m), remote: true, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar el Marcador?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<button class="btn btn-danger btn-md active"><%= link_to 'Volver al Inicio', root_path, class:'text-white'%></button>

app/views/markers/new.html.erb
<h1>Markers#new</h1>
<p>Find me in app/views/markers/new.html.erb</p>

app/views/markers/new.js.erb
$('#form').append('<%= escape_javascript render('markers/form') %>');
    $("#submit").click(function(){
    $("#form").slideUp("slow");
});
$('#mybutton').hide();

app/views/markers/show.html.erb
<h3 class="category-title text-center">Listado de Marcadores</h3>

<table class="table table-striped">
    <thead id="tabla">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody id="markers">
        <% @markers.each do |m| %>
            <tr>
                <td><%= m.id %></td>
                <td><%= m.name %></td>
                <td><%= link_to 'Editar', edit_marker_path(m) %></td>
                <td><%= link_to 'Eliminar', marker_path(m), method: :delete, data: { confirm: '¿Esta seguro que desea eliminar el Marcador?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<button class="btn btn-danger btn-md active"><%= link_to 'Volver al Inicio', root_path, class:'text-white'%></button>

app/views/markers/update.html.erb
<h1>Markers#update</h1>
<p>Find me in app/views/markers/update.html.erb</p>

app/views/markers/update.js.erb
$('#marker-<%=@marker.id%>').replaceWith('<%= j render(@marker, post: @marker) %>');
$("#form").empty();